#spring:
#  application:
#    name: chat
#  data:
#    redis:
#      host: localhost
#      port: 6379
#server:
#  port: 8084

spring:
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        service-id: config
        enabled: true
      name: chat
      profile: dev

