spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/glaptev8/letsToGether
          searchPaths: config/src/main/resources
          clone-on-start: true
          force-pull: true
  profiles:
    active: dev
