spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  r2dbc:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${LETS_TO_GETHER_IP}/eureka/