spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/glaptev8/letsToGether
          searchPaths: config/src/main/resources
          clone-on-start: true
          force-pull: true
  application:
    name: config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/