spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  r2dbc:
    username: postgres
    password: postgres
  flyway:
    user: postgres
    password: postgres
server:
  port: 8081
