spring:
  application:
    name: authentication
  r2dbc:
    url: ${R2DBC_DATASOURCE_URL}
  flyway:
    url: ${FLYWAY_DATASOURCE_URL}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: name

jwt:
  secret: 426b1066314ea793aa5d0907d7323310eef672ab280958f1f667be70c61c9abf
  expiration: 3600
  issuer: letstogether

upload:
  path: {AVATAR_FOLDER_PATH}