spring:
  application:
    name: event
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/event
  flyway:
    url: jdbc:postgresql://localhost:5432/event
  rabbitmq:
    host: localhost
    port: 5673
    username: user
    password: password
server:
  port: 8083