server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: lb://authentication # Используйте имя сервиса авторизации, зарегистрированное в Eureka
          predicates:
            - Path=/auth/** # Предполагаем, что все запросы к сервису авторизации идут через /auth
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}