spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: lb://authentication
          predicates:
            - Path=/auth/**,/oauth2/**,/login/**
        - id: event
          uri: lb://event
          predicates:
            - Path=/event/**
        - id: chat
          uri: lb://chat
          predicates:
            - Path=/chat/**
      websocket:
        enabled: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${LETS_TO_GETHER_UI}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      global-filter:
        websocket-routing:
          enabled: true