server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: lb://authentication
          predicates:
            - Path=/auth/**
        - id: event
          uri: lb://event
          predicates:
            - Path=/event/**
        - id: chat
          uri: lb://chat
      websocket:
        enabled: true