server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: lb://authentication
          predicates:
            - Path=/auth/**,/oauth2/**
        - id: event
          uri: lb://event
          predicates:
            - Path=/event/**
        - id: chat
          uri: lb://chat
          predicates:
            - Path=/chat/**
      websocket:
        enabled: true