version: "3.9"

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data2/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nexus:
    image: klo2k/nexus3
    container_name: nexus
    ports:
      - "8090:8081"
    volumes:
      - ./nexus-data:/nexus-data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "myrabbitmq:3-management"
    ports:
      - "5673:5672" # AMQP protocol
      - "15673:15672" # Web management interface
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  lets-to-gether-ui:
    image: "glaptev8/lets-to-gether-ui:0.0"
    environment:
      VITE_LETS_TO_GETHER_GATEWAY: "http://lets-to-gether-gateway:8080"
    ports:
      - "3000:80"
    pull_policy: always
  lets-to-gether-eureka:
    image: "glaptev8/lets-to-gether-eureka:0.0"
    ports:
      - "8761:8761"
  lets-to-gether-config:
    image: "glaptev8/lets-to-gether-config:0.0"
    ports:
      - "8080:8080"
    environment:
      LETS_TO_GETHER_EUREKA_IP: "http://lets-to-gether-eureka:8761/eureka/"
      DATASOURCE_USERNAME: "postgres"
      DATASOURCE_PASSWORD: "postgres"
      SPRING_PROFILES_ACTIVE: "qa"
  lets-to-gether-gateway:
    image: "glaptev8/lets-to-gether-gateway:0.0"
    ports:
      - "8082:8080"
    environment:
      LETS_TO_GETHER_UI: "http://lets-to-gether-ui:80"
      LETS_TO_GETHER_CONFIG: "http://lets-to-gether-config:8080"
      LETS_TO_GETHER_EUREKA_IP: "http://lets-to-gether-eureka:8761/eureka/"
      SPRING_PROFILES_ACTIVE: "qa"
  lets-to-gether-authentication:
    image: "glaptev8/lets-to-gether-authentication:0.0"
    volumes:
      - /Users/glelap/projects/letsToGether/static/:/app/static
    environment:
      LETS_TO_GETHER_UI_IRI: "http://localhost:3000"
      LETS_TO_GETHER_CONFIG: "http://lets-to-gether-config:8080"
      LETS_TO_GETHER_EUREKA_IP: "http://lets-to-gether-eureka:8761/eureka/"
      DATASOURCE_USERNAME: "postgres"
      DATASOURCE_PASSWORD: "postgres"
      R2DBC_DATASOURCE_URL: "r2dbc:pool:postgres://postgres:5432/authentication"
      FLYWAY_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/authentication"
      SPRING_PROFILES_ACTIVE: "qa"
      CLIENT_ID: "707124684633-7e5hqvfuua6vivmg7d7uoha52lhevs3b.apps.googleusercontent.com"
      CLIENT_SECRET: "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"
      GOOGLE_REDIRECT_URI: "http://lets-to-gether-gateway:8082/login/oauth2/code/google"
      AVATAR_FOLDER_PATH: "/app/static"