version: "3.9"

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data2/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nexus:
    image: klo2k/nexus3
    container_name: nexus
    ports:
      - "8090:8081"
    volumes:
      - ./nexus-data:/nexus-data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "myrabbitmq:3-management"
    ports:
      - "5673:5672" # AMQP protocol
      - "15673:15672" # Web management interface
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  lets-to-gether-ui:
    image: "glaptev8/lets-to-gether-ui:0.0"
    ports:
      - "3000:80"
  lets-to-gether-eureka:
    image: "glaptev8/lets-to-gether-eureka:0.0"
    ports:
      - "8761:8761"