version: "3.9"

services:
  postgres:
    image: postgres
    volumes:
      - ./data2/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  nexus:
    image: klo2k/nexus3
    container_name: nexus
    ports:
      - "8090:8081"
    volumes:
      - ./nexus-data:/nexus-data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "myrabbitmq:3-management"
    ports:
      - "5673:5672" # AMQP protocol
      - "15673:15672" # Web management interface
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5