/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TokenDetails', function() {
      beforeEach(function() {
        instance = new OpenApiDefinition.TokenDetails();
      });

      it('should create an instance of TokenDetails', function() {
        // TODO: update the code to test TokenDetails
        expect(instance).to.be.a(OpenApiDefinition.TokenDetails);
      });

      it('should have the property userId (base name: "userId")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property token (base name: "token")', function() {
        // TODO: update the code to test the property token
        expect(instance).to.have.property('token');
        // expect(instance.token).to.be(expectedValueLiteral);
      });

      it('should have the property issuedAt (base name: "issuedAt")', function() {
        // TODO: update the code to test the property issuedAt
        expect(instance).to.have.property('issuedAt');
        // expect(instance.issuedAt).to.be(expectedValueLiteral);
      });

      it('should have the property expiresAt (base name: "expiresAt")', function() {
        // TODO: update the code to test the property expiresAt
        expect(instance).to.have.property('expiresAt');
        // expect(instance.expiresAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
