/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TokenDetails model module.
 * @module model/TokenDetails
 * @version v0
 */
export default class TokenDetails {
  /**
   * Constructs a new <code>TokenDetails</code>.
   * @alias module:model/TokenDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TokenDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TokenDetails} obj Optional instance to populate.
   * @return {module:model/TokenDetails} The populated <code>TokenDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TokenDetails();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('issuedAt'))
        obj.issuedAt = ApiClient.convertToType(data['issuedAt'], 'Date');
      if (data.hasOwnProperty('expiresAt'))
        obj.expiresAt = ApiClient.convertToType(data['expiresAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} userId
 */
TokenDetails.prototype.userId = undefined;

/**
 * @member {String} token
 */
TokenDetails.prototype.token = undefined;

/**
 * @member {Date} issuedAt
 */
TokenDetails.prototype.issuedAt = undefined;

/**
 * @member {Date} expiresAt
 */
TokenDetails.prototype.expiresAt = undefined;

