/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The V1RegisterBody model module.
 * @module model/V1RegisterBody
 * @version v0
 */
export default class V1RegisterBody {
  /**
   * Constructs a new <code>V1RegisterBody</code>.
   * @alias module:model/V1RegisterBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1RegisterBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1RegisterBody} obj Optional instance to populate.
   * @return {module:model/V1RegisterBody} The populated <code>V1RegisterBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1RegisterBody();
      if (data.hasOwnProperty('avatar'))
        obj.avatar = ApiClient.convertToType(data['avatar'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Blob} avatar
 */
V1RegisterBody.prototype.avatar = undefined;

